raft.enabled=true
raft.node.id=node-3
raft.node.host=ledger-3
raft.node.port=9866
server.port=8082

raft.peers=node-1:ledger-1:9864,node-2:ledger-2:9865,node-3:ledger-3:9866
raft.group.id=chaosledger-group
raft.storage.dir=/data/raft

spring.datasource.url=jdbc:postgresql://postgres-3:5432/chaosledger
spring.datasource.username=postgres
spring.datasource.password=postgres